// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXwq4sx9beb5YPwZ431m9ETmhaEBDg_Is',
    appId: '1:938324403295:web:0f263f8b799b335ccf27ea',
    messagingSenderId: '938324403295',
    projectId: 'assignment-a4e12',
    authDomain: 'assignment-a4e12.firebaseapp.com',
    storageBucket: 'assignment-a4e12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfs46vF-KO6UCicn3_kY7VFkeHc8jbF9U',
    appId: '1:938324403295:android:74fc7ba094b85f0ecf27ea',
    messagingSenderId: '938324403295',
    projectId: 'assignment-a4e12',
    storageBucket: 'assignment-a4e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASam1wt-Y8ZsJ1C6U8QisRRmwkDoFnWp8',
    appId: '1:938324403295:ios:387937e366646870cf27ea',
    messagingSenderId: '938324403295',
    projectId: 'assignment-a4e12',
    storageBucket: 'assignment-a4e12.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASam1wt-Y8ZsJ1C6U8QisRRmwkDoFnWp8',
    appId: '1:938324403295:ios:387937e366646870cf27ea',
    messagingSenderId: '938324403295',
    projectId: 'assignment-a4e12',
    storageBucket: 'assignment-a4e12.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXwq4sx9beb5YPwZ431m9ETmhaEBDg_Is',
    appId: '1:938324403295:web:bc4dc83ce42a10d1cf27ea',
    messagingSenderId: '938324403295',
    projectId: 'assignment-a4e12',
    authDomain: 'assignment-a4e12.firebaseapp.com',
    storageBucket: 'assignment-a4e12.firebasestorage.app',
  );
}
